{
  "name" : "Default experiment name",
  "model" : {
    "name" : "cannonball.model",
    "odeList" : [ {
      "leftHandSide" : "v",
      "rightHandSide" : "-g"
    }, {
      "leftHandSide" : "y",
      "rightHandSide" : "v"
    } ],
    "areOdesValid" : true,
    "unboundParameters" : [ ]
  },
  "parameterValues" : [ 9.81 ],
  "stateValues" : [ 30.0, 0.0 ],
  "timeValues" : [ 0.0, 10.0, 0.01 ]
}