{
  "name" : "Default experiment name",
  "model" : {
    "name" : "harmonic_motion.model",
    "odeList" : [ {
      "leftHandSide" : "theta",
      "rightHandSide" : "omega"
    }, {
      "leftHandSide" : "omega",
      "rightHandSide" : "-m*omega-(g/L)*sin(theta)"
    } ],
    "areOdesValid" : true,
    "unboundParameters" : [ ]
  },
  "parameterValues" : [ 2.0, 9.81, 0.5 ],
  "stateValues" : [ 0.0, 3.0 ],
  "timeValues" : [ 0.0, 10.0, 0.1 ]
}