{
  "name" : "Default experiment name",
  "model" : {
    "name" : "test.model",
    "areEquationsValid" : true,
    "unboundParameters" : [ ],
    "varDescription" : {
      "A" : [ "m", "" ],
      "B" : [ "km", "Example" ],
      "C" : [ "", "" ],
      "k1" : [ "m/s", "" ],
      "k2" : [ "km/u", "" ],
      "k3" : [ "", "" ]
    },
    "equationList" : [ {
      "@class" : "smrt2.Ode",
      "leftHandSide" : "A",
      "rightHandSide" : "k1+4"
    }, {
      "@class" : "smrt2.AlgEq",
      "leftHandSide" : "B",
      "rightHandSide" : "A+k2+4"
    } ]
  },
  "parameterValues" : [ 5.0, 1.0 ],
  "stateIntialValues" : [ 1.0, 1.0 ],
  "timeValues" : [ 2019.0, 2050.0, 1.0 ]
}